// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCrv_ystNwl7c0hpTgxuFnMZ2y_o4mX3M',
    appId: '1:272083071155:web:14c8e55754a445a5ef40c6',
    messagingSenderId: '272083071155',
    projectId: 'flutterchatapp-2387a',
    authDomain: 'flutterchatapp-2387a.firebaseapp.com',
    storageBucket: 'flutterchatapp-2387a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJewRnk7oBIIH9kIXL4h6LCPFokVHI81I',
    appId: '1:272083071155:android:d1a8e14587be8bc3ef40c6',
    messagingSenderId: '272083071155',
    projectId: 'flutterchatapp-2387a',
    storageBucket: 'flutterchatapp-2387a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtIDp52YgPJFjollofWdXTN9-tSw0wYyQ',
    appId: '1:272083071155:ios:767c36d020125a0aef40c6',
    messagingSenderId: '272083071155',
    projectId: 'flutterchatapp-2387a',
    storageBucket: 'flutterchatapp-2387a.appspot.com',
    iosClientId: '272083071155-s6vcnk7jmj90iac9h86qhqib00536i06.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatappFirebase',
  );
}
